"""add_address_and_image_to_queue

Revision ID: d3f58d6222c5
Revises: 
Create Date: 2026-01-12 11:07:41.782146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f58d6222c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queues', sa.Column('address', sa.String(), nullable=True))
    op.add_column('queues', sa.Column('image_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queues', 'image_name')
    op.drop_column('queues', 'address')
    # ### end Alembic commands ###